# Site settings
title: Adhit's Blog
email: adhit.simhadri@gmail.com
description: "Step by step, building a whole new universe out there"
baseurl: ""
url: ""
twitter_username: ErizoSamurai
github_username:  erizosamurai 

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
